# Generated by Django 5.0.3 on 2024-05-30 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_auction_listing_watch_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='watch_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='watch_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
