# Generated by Django 5.0.3 on 2024-06-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comments_listing_comments_message_comments_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='watch_list',
            new_name='watchlist',
        ),
    ]
