# Generated by Django 5.0.3 on 2024-06-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bids_bid_bids_listing_bids_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
